//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTasks_Statuses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statuses
    {
        public int Status_ID { get; set; }
        public string Status_name { get; set; }
    }
}
